language: rust
rust:
- nightly
cache: cargo
env:
  matrix:
  - RELEASE_FLAG=""
  - RELEASE_FLAG="--release"
  global:
    secure: "crlyJROHoJr4i4EVS+E3ecBGUosL+hwQIYHoroJ5B6M8ROUpPb8yTERSd/eaCEoSmsbuop4d11LVOtYUusSXrhEtweuLsMyvZ3DsVBZzT86iRjDxJbb2bb4gzAt71LOrSu07G+zYNxxqTnbJWoVKYaalrjKT/1uztvXHfHrCZ43p77fdiATfCzNGvI71aC5E04O48bXoBL/Fme+oagF+IqxtuOCkNBdDmd8JfLpziIgGK5YOeYa3Ix2Uydy7wQK5igeqosgNq+l7Z7NNCM46rFx3nLfGC5/gIKh3A4QpEdX2X+Asw2s62jn5M4lJ4/HYbl/qRALqntjWCY7MR4P4KJBbfcH1zTFL+GxQroPh0KlDLN/uw5dx5UmdLzSNPdUedaifBMNYB1w0I2t2bH6qJV8SW2Xbgqu2DPi0+Hh7hV8Z+50SyDxF/BbgziAIGqZe6tD+z6NQLCdZsBoXS/4PtY2EzlAGHijofdVwryYYYBGmnoMpG1ebTrnnh2mc3VB7Hm9BK6r3BrtBIRposRksbuc6dMR0UwJB27ruTuzPEBuM3GyvPRvrIqgs6TrM3C7oXDy48fgMh3wkGM+FQphfxqMWkdwKYs9AGJ4QYnoZCSJYQrd1dnKDLO+RlLLqTBqFTrir4PG4FgZS6UdU6Xn4MawsWvyBvFVc4iLtfu7L958="
install:
- export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo "-Z external-macro-backtrace")
- "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f 1)"
script:
- cargo fmt --all -- --check
- cargo check --all --verbose $RELEASE_FLAG
- cargo build --all --verbose $RELEASE_FLAG
- cargo test --all --verbose $RELEASE_FLAG
- cargo doc --all --verbose $RELEASE_FLAG
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: target/doc
  on:
    branch: master
    condition: $RELEASE_FLAG = --release
