language: rust
rust:
- nightly
cache: cargo
env:
  matrix:
  - RELEASE_FLAG=""
  - RELEASE_FLAG="--release"
  global:
    secure: "B+xaKRytH8KfvYMnd37iQJbZLVPOqEiLdZj+bo/hzVP4rzs9gTUzyfo2wqvAgwN+BvlcZ+sgu51njw0N9PtmeevABsgOegbByC9imP3m9ZhrIK+HYUHxUsobRYH1FmGpxSDoGDO7T4u4+Fb+5duNN2aAZ/vge7ibBNja+Cj8ryZZsrnCvJVGZrG+9IuuWuM4mOv6+F3EERz2Cx9UjMW99EF4tnme1njNooNRGx2rMM9jJAyEht0HYRomivuc75i7hY7gQrzWHnI97JryT3rmebOI9hlC+zDIKtwfLq7rGFSCogswUzXyA2sHApxyLGrP1LDBEE+0CLnkYNfPH+HpI7PhwJPJFyRTNfjU7YWgKiViPTls6xR+6RUuOKa9RAnrd/FkOHzSEV07TnPa3xofYTf4UJTbpWckHJjQ1jmQlXE3HE+q1+AYf4YzYIcxocJdSAUniE50tRz7so/uTihYFW7uJ0EcQQpJyojd8VUOUYJT3oWYcswRwLrZA1JqL4wz+4x0mao8f/lI0JjVhFviXP44qAxPM5QGItSdXsaaFiOhdqHcaELpP5qkolurK3q7cgIQyvOTCmXcuGvujtkHcAMrT6+8Wv2Y3yRA/P6X4nyX4g0ySC/MuqJTwDaXpclsNzMlgXzjzCjXiD2NjVNKHuTIre77PzD8TIYWyyRu59E="
install:
- export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo "-Z external-macro-backtrace")
- "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f 1)"
script:
- cargo fmt --all -- --check
- cargo check --all --verbose $RELEASE_FLAG
- cargo build --all --verbose $RELEASE_FLAG
- cargo test --all --verbose $RELEASE_FLAG
- cargo doc --all --verbose $RELEASE_FLAG
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: target/doc
  on:
    branch: master
    condition: $RELEASE_FLAG = --release
