[workspace]
members = [".", "octorest-routes"]

[package]
name = "octorest"
version = "0.1.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/SOF3/octorest.git"
homepage = "https://github.com/SOF3/octorest"

[dependencies]
async-trait = "0.1.11"
derive_more = "0.15.0"
derive-new = "0.5.8"
getset = "0.0.8"
octorest-routes = {version = "0.1.0", path = "octorest-routes"}
reqwest = "0.9.20"
static_assertions = "0.3.4"

[badges]
travis-ci = {repository = "SOF3/octorest"}
