name: Docs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: default
      - run: "wget -O build/api.github.com.json $(curl -H \"Authorization: header ${{secrets.GH_TOKEN}}\" https://api.github.com/repos/octokit/routes/releases/latest | jq -r '.assets | map(select(.name == \"api.github.com.json\")) | first | .browser_download_url')"
      - run: cargo +nightly doc --no-deps --features internal-docsrs
      - run: git fetch && git checkout gh-pages
      - run: test ! -d $(echo ${{github.ref}} | cut -d/ -f3) || rm -r $(echo ${{github.ref}} | cut -d/ -f3)
      - run: cp -r target/doc $(echo ${{github.ref}} | cut -d/ -f3)
      - run: git config --local user.name "github-actions[bot]" && git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add $(echo ${{github.ref}} | cut -d/ -f3) && git commit -m "Docs build for SOF3/octorest@${{github.sha}}"
      - run: git push
